apiVersion: nodemaintenance.kubevirt.io/v1beta1
kind: NodeMaintenance
metadata:
  name: nodemaintenance-sample-worker-0
spec:
  nodeName: ci-ln-xyrv0n2-72292-nzlrn-worker-a-s8mfh
  reason: "Test workload availability worker 0"